# Numpy

### Basic Array Operation's

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
a = [1,2,3,4.4, "Tejas"]
a

[1, 2, 3, 4.4, 'Tejas']

In [4]:
np.array(a)

array(['1', '2', '3', '4.4', 'Tejas'], dtype='<U32')

### Vectors - 1D Array
### Matrices - 2D Array
### Tensors - 3D Array

In [5]:
l = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generations functions

In [7]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [9]:
arr1 = np.zeros((5,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr = np.linspace(1, 5, 10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### Random Generation Function

In [12]:
np.random.rand(5)

array([0.50614923, 0.41255395, 0.82027045, 0.32356182, 0.88306032])

In [13]:
np.random.randn(10)

array([-0.46563285,  0.08248213,  0.37607458,  0.37483942,  1.49490199,
       -0.87286555, -0.11893803, -0.27622189, -0.11702694, -2.55717957])

In [14]:
np.random.randint(10,20)

15

In [15]:
np.random.randint(10,20, 5)

array([19, 19, 11, 14, 15], dtype=int32)

### Array Attributes

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

###  Array Method

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [24]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.std()

np.float64(2.581988897471611)

In [27]:
arr.argmax()

np.int64(8)

In [28]:
arr.argmin()

np.int64(0)

### Reshaping and resizing

In [35]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
### Array Indexing and Sclicing of Vectors

In [20]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
arr[6]

17

In [23]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [24]:
arr[0:5:2]

array([11, 13, 15])

### Numpy Indxing and Sclicing of Matrix

In [28]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
arr[0]

array([1, 2, 3, 4, 5])

In [31]:
arr[0,0]

1

### Boolean Indexing

In [36]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
booaln_index = arr % 2 == 0
booaln_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [37]:
arr = arr[booaln_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Numpy - Array Operations

In [38]:
import numpy as np

**Arithmatic Operations**

In [40]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [41]:
a3 = a1 + a2
a3

array([ 7,  9, 11, 13, 15])

a3 = a1 - a2
a3

In [44]:
a3 = a1 ** a2
a3

array([      1,     128,    6561,  262144, 9765625])

**Brodcasting**

In [47]:
l = [10,20,30,40]
arr = np.array(l)
arr 

array([10, 20, 30, 40])

In [48]:
arr + 10

array([20, 30, 40, 50])

**Deep and Shallow Copy**

In [49]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [54]:
a  # Deep Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
b = a.copy()  # Shallow Copy
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
b[0] = 1000
b

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

**Matrix Operations**

In [72]:
A = np.array(([1,2],[4,5]))
B = np.array(([7,8],[9,10]))

In [73]:
A

array([[1, 2],
       [4, 5]])

In [74]:
B

array([[ 7,  8],
       [ 9, 10]])

In [75]:
A * B

array([[ 7, 16],
       [36, 50]])

In [77]:
A @ B  # . Multiplication

array([[25, 28],
       [73, 82]])

**Transpose of a Matrix**

In [78]:
A.T

array([[1, 4],
       [2, 5]])

### Advance Array Manuplations

In [79]:
A

array([[1, 2],
       [4, 5]])

In [80]:
B

array([[ 7,  8],
       [ 9, 10]])

In [81]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [83]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splicting Array**

In [86]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

*Thank-you 🙌*